### PR TITLE
Translate2

### PR DESCRIPTION
**Pull request by tingley**
Proposed changes to translation tasks, plus general cleanup:
* Standardize attribute names to camel case
* Add optional `workDir` parameter for tkit location
* Change default target file naming scheme, allow customization via template
* Remove example-usage.xml, split it out into task-specific files in `examples/`

### CODE REVIEW

**Comment by tingley** [comment]
Sticking this here as a PR so @amake can take a look.

**Comment by amake** [comment]
These files are generated dynamically by OmegaT and don't need to be committed:

```
examples/post-translate/tkits/Translate_fr-fr/Translate_fr-fr-level1.tmx
examples/post-translate/tkits/Translate_fr-fr/Translate_fr-fr-level2.tmx 
examples/post-translate/tkits/Translate_fr-fr/omegat/ignored_words.txt
examples/post-translate/tkits/Translate_fr-fr/omegat/last_entry.properties
examples/post-translate/tkits/Translate_fr-fr/omegat/learned_words.txt
examples/post-translate/tkits/Translate_fr-fr/omegat/project_save.tmx.201512261627.bak
examples/post-translate/tkits/Translate_fr-fr/omegat/project_stats.txt
```

**Comment by amake** [comment]
Is the idea with the examples that they can be run with just `ant` as-is from a fresh checkout? If so, we should commit the contents of `examples/post-translate/tkits/Translate_fr-fr/target` that is generated by OmegaT's `Create Translated Documents` command. Otherwise you have to actually open the sample tkit in OmegaT and do the command, but it's a big pain for a couple reasons:

1. OmegaT thinks the tkit is a team project because it's under git, so it does some annoying stuff like checks out `master` and might revert some changes
2. It yells at you that `target`, `tm`, `dictionary`, and `glossary` dirs are missing from the project (they're not in git because git can't keep empty dirs)

**Comment by amake** [comment]
Other than the above everything looks good.

**Comment by tingley** [comment]
Thanks, I've removed the extra post-translate files (commit faf578a4).

The goal was to make them easy to run, and I had noticed the issue with OmegaT getting confused by the .git directory.  I had put a note in the wiki docs about this, but you're right, just committing the results (as we have in post-translate) to the translate example makes more sense..

**Comment by tingley** [comment]
Source control made that ugly, so I ended up putting the translated xliff in a completed directory and splitting out a different target ("ant complete") to copy it into the kit and then run the translate task.

**Pull request merged**
